name: Deploy React App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: secrets
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd ./BondB
          git pull origin main
          npm install --production
          npm run build
          pm2 stop react-app || true
          pm2 start serve --name "react-app" -- -s build -l 3000
